# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fee3250c8b9673e6dfac8e2e12d2b5e476e43a43eaf3bb19f821a9e9474457a23592ccebc4cb439ca2c01f8910f2cf1a03ac57a426b31e7b8c04550b0f417de9

test:
  secret_key_base: 00324abf0a22696f124317901af3936ec7accb6e4696015542f0af3a61e4edcafebcdecaa6b8eb43e43565af36c64c285e55b1a3547467fb31c64c5b599e0f82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
